### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by lechen26** [cardinalby/webext-buildtools-chrome-crx-action#1]
i've used it the same as in the example
```
name: CI

on:
  push:
    branches: [ci-cd]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
     - uses: actions/checkout@v1
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v1
       with:
         node-version: ${{ matrix.node-version }}
     - uses: cardinalby/webext-buildtools-chrome-crx-action@v1
       with:
         extensionDir: 'extension'
         crxFilePath: 'extension.crx'
         privateKey: ${{ secrets.CHROME_KEY }}
     - run: ls -l 
```

in my extension dir i have the chrome extension and at the end of the workflow nothing happens and there is no output crx file.
